export default {
    FormRepository: Symbol.for('FormRepository'),
    FormService: Symbol.for('FormService'),
    FormVersionRepository: Symbol.for('FormVersionRepository'),
    RoleRepository: Symbol.for('RoleRepository'),
    SequelizeProvider: Symbol.for('SequelizeProvider'),
    FormSchemaValidator: Symbol.for('FormSchemaValidator'),
    KeycloakService: Symbol.for('KeycloakService'),
    ProtectMiddleware: Symbol.for('ProtectMiddleware'),
    FormCommentRepository: Symbol.for('FormCommentRepository'),
    ValidationService: Symbol.for('ValidationService'),
    RoleService: Symbol.for('RoleService'),
    FormResourceAssembler: Symbol.for('FormResourceAssembler'),
    AdminProtectMiddleware: Symbol.for('AdminProtectMiddleware'),
    CommentService: Symbol.for('CommentService'),
    AppConfig: Symbol.for('AppConfig'),
    EventEmitter: Symbol.for('EventEmitter'),
    PDFService: Symbol.for('PDFService'),
    PDFQueue: Symbol.for('PDFQueue'),
    CacheManager: Symbol.for('CacheManager'),
    JsonPathEvaluator: Symbol.for('JsonPathEvaluator'),
};
